const assetUrl=path=>window.REVO_INLINE_ASSETS?.[path]||path;
const streams=[
['Diversion from landfill','A new route for challenging waste.','We look beyond disposal to find practical recycling and reuse opportunities for difficult materials. Let’s explore what’s possible for your waste stream.',['Assessment','Reuse','Recovery']],
['E-waste','Old electronics. New possibilities.','Manual dismantling separates electronic waste into plastics, metals, cables and circuit boards. RevoWaste’s existing service information lists dismantling facilities in Gauteng, KwaZulu-Natal and Cape Town. Ask our team about the right route for your equipment.',['Electronics','Components','Material recovery']],
['Printer cartridges','An empty cartridge still has value.','Our cartridge recycling process achieves a reported 99% recycling rate. Cartridges are dismantled by hand to separate materials for reuse and recycling, with less than 1% going to landfill.',['Toner cartridges','Office waste','99% recycling rate']],
['Scrap metals','Keep valuable metals in circulation.','We accept a wide range of scrap metals, including steel, aluminium, copper, brass, cast iron, bronze, metal shavings and copper cables. Tell us about the type, quantity and condition of your material.',['Steel','Aluminium','Copper & more']],
['Plastics','Reimagine the life of plastic.','Plastics are sorted by type and grade, granulated and processed into pellets for use as raw materials. Local processing supports South African manufacturing. Accepted types include HDPE, LDPE, PP, PET and ABS; suitability depends on the material.',['Rigid plastics','Mixed streams','Circular materials']],
['Foams & sponges','A softer material. A smarter solution.','After other materials and contaminants are removed, foam and sponge can be granulated into smaller pieces for use by other industries. Ask us to assess the recycling or reuse potential of your material.',['Foam','Sponge','Reuse opportunities']],
['Waste management','A better system starts at your site.','From recycling teams at your premises to skip bins and waste removal, we build a practical system around your operation. Reporting tracks waste removed, recycled, reused and landfilled, helping you measure progress towards your goals.',['Site assessment','Tailored solutions','Reporting']],
['Batteries','A responsible next step for batteries.','RevoWaste offers recycling for all battery chemistries. Share the battery type, quantity and condition with our team to discuss appropriate arrangements and pricing.',['Battery waste','Material assessment','Specialist guidance']]
];
const streamPictures=[['p3.jpg','Mixed plastic materials from the original RevoWaste gallery'],['item-7.jpg','Electronics being manually dismantled'],['pr3.jpg','Used printer cartridges'],['m3.jpg','Scrap metal in a collection bin'],['p2.jpg','Granulated plastic flakes'],['item-14.jpg','Foam offcuts collected together'],['w3.jpg','A waste collection skip'],['b1.jpg','Battery recycling materials']];
const list=document.querySelector('.stream-list');list.innerHTML=streams.map((s,i)=>`<button id="stream-${i}" role="tab" aria-selected="${i===0}" aria-controls="stream-panel" tabindex="${i===0?0:-1}" data-stream="${i}"><span class="num">0${i+1}</span>${s[0]}<span class="arrow"></span></button>`).join('');
function selectStream(i){const s=streams[i];list.querySelectorAll('button').forEach((b,j)=>{b.setAttribute('aria-selected',j===i);b.tabIndex=j===i?0:-1});const panel=document.querySelector('#stream-panel');panel.setAttribute('aria-labelledby',`stream-${i}`);panel.innerHTML=`<img class="stream-photo" src="${assetUrl(''+streamPictures[i][0])}" alt="${streamPictures[i][1]}" loading="lazy"><span class="detail-number" aria-hidden="true">0${i+1}</span><p class="eyebrow">${s[0]}</p><h3>${s[1]}</h3><p>${s[2]}</p><div class="tags">${s[3].map(t=>`<span>${t}</span>`).join('')}</div><a class="text-link" href="#contact">Let’s talk ${s[0].toLowerCase()} <span></span></a>`;panel.querySelector('a').onclick=()=>{document.querySelector('#enquiry [name=stream]').value=['Diversion from landfill','E-waste','Printer cartridges','Scrap metals','Plastics','Foams and sponges','Waste management','Batteries'][i]}}list.addEventListener('click',e=>{let b=e.target.closest('button');if(b)selectStream(Number(b.dataset.stream))});selectStream(0);
const impacts={green:['A choice that moves us forward.','Choose reuse and recycling where suitable routes exist. Keep materials separated and explore products or processes that reduce waste. The green turtle celebrates positive steps towards a healthier environment.'],orange:['Good potential. A little more care.','Some materials need extra sorting, preparation or specialist processing. The orange turtle asks us to pause, find out more and improve the route we choose, rather than assume something is ready to recycle.'],red:['Pause. Rethink. Find a better route.','Practices that harm the environment need a different approach. The red turtle is a reminder to reduce waste, avoid pollution and seek expert advice when a material is difficult to manage.']};
function selectImpact(key){document.querySelectorAll('[data-impact]').forEach(b=>{let on=b.dataset.impact===key;b.setAttribute('aria-selected',on);b.tabIndex=on?0:-1});let p=document.querySelector('#impact-panel');p.setAttribute('aria-labelledby','impact-'+key);p.innerHTML=`<h3>${impacts[key][0]}</h3><p>${impacts[key][1]}</p>`}document.querySelector('.turtle-options').addEventListener('click',e=>{let b=e.target.closest('button');if(b)selectImpact(b.dataset.impact)});selectImpact('green');
const steps=[['Understand your site','We begin with a conversation and a site assessment to understand your operation, materials and goals.'],['Shape your solution','A tailored proposal sets out the approach for your business to consider.'],['Put the plan in place','The agreed waste management solution is set up at your premises.'],['Receive the materials','Collected waste arrives at a RevoWaste facility for the next stage of its journey.'],['Measure and document','Collection notes, weight slips and recycling certificates document the journey. Clients with teams on their premises receive monthly reports, and records are retained for at least five years.'],['Process and recycle','Materials move through suitable recycling and recovery processes.'],['Return materials to use','Recovered resources return to the market for further use.']];let currentStep=0;const stepList=document.querySelector('.steps');stepList.innerHTML=steps.map((s,i)=>`<button id="step-${i}" role="tab" aria-controls="step-panel" data-step="${i}"><span>0${i+1}</span>${s[0]}</button>`).join('');function selectStep(i){currentStep=i;stepList.querySelectorAll('button').forEach((b,j)=>{b.setAttribute('aria-selected',j===i);b.tabIndex=j===i?0:-1});const p=document.querySelector('#step-panel');p.setAttribute('aria-labelledby',`step-${i}`);p.innerHTML=`<img class="process-photo" src="${assetUrl('step'+(i+1)+'.jpg')}" alt="${i===3?'RevoWaste facility exterior':'Illustration of '+steps[i][0].toLowerCase()}" loading="lazy"><span class="step-big">0${i+1}</span><h3>${steps[i][0]}</h3><p>${steps[i][1]}</p><div class="step-navigation"><button type="button" id="prev-step" aria-label="Previous step">←</button><small>STEP ${i+1} OF 7</small><button type="button" id="next-step" aria-label="Next step">→</button></div>`;document.querySelector('#prev-step').onclick=()=>selectStep((currentStep+6)%7);document.querySelector('#next-step').onclick=()=>selectStep((currentStep+1)%7)}stepList.onclick=e=>{let b=e.target.closest('button');if(b)selectStep(Number(b.dataset.step))};selectStep(0);
document.querySelectorAll('[role=tablist]').forEach(el=>el.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','ArrowDown','ArrowUp','Home','End'].includes(e.key))return;e.preventDefault();const bs=[...el.querySelectorAll('[role=tab]')];let i=bs.indexOf(document.activeElement);if(i<0)return;i=e.key==='Home'?0:e.key==='End'?bs.length-1:(i+(['ArrowRight','ArrowDown'].includes(e.key)?1:bs.length-1))%bs.length;bs[i].click();bs[i].focus()}));
const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu.onclick=()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus()}});
document.querySelector('#year').textContent=new Date().getFullYear();
// A symbolic ocean story. The levels are narrative, not scientific measurements.
const scene=document.querySelector('.ocean-experience');
const turtleImage=document.querySelector('#scene-turtle');
const turtleButton=document.querySelector('.turtle-touch');
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
const wasteSlider=document.querySelector('#waste-level');
const litterField=document.querySelector('#litter-field');
let wasteLevel=0,motionPaused=reducedMotion.matches,recoveryTimer=null,tipIndex=0,manualStory=false;
const oceanStories={
 green:{kicker:'01 / A WORLD WORTH PROTECTING',title:'Let this be the future.',story:'Scroll to follow the story, or explore it with the controls. Every choice changes what happens next.',state:'CLEAR WATERS',tips:['My colours tell the story of our choices. They are a symbol, not a change real turtles experience.','The best place to stop ocean pollution is before waste reaches the water.']},
 orange:{kicker:'02 / THE RIPPLE OF A SMALL CHOICE',title:'It never just disappears.',story:'A few discarded items begin to change the scene. Our turtle turns amber as a reminder to act before waste travels further.',state:'PRESSURE IS BUILDING',tips:['Waste dropped on land can travel through drains and rivers. The ocean is connected to our everyday choices.','Collecting waste helps, but preventing it and finding reuse routes are where lasting progress begins.']},
 red:{kicker:'03 / THE COST OF LOOKING AWAY',title:'This is not where it belongs.',story:'The water darkens. Waste crowds the turtle. Red is our signal to change the story. Start recovering what we can.',state:'TIME TO CHANGE THE STORY',tips:['Plastic pollution can put marine life at risk. Our red turtle asks us to choose a better route for waste.','A clean scene is easy to restore here. In the real world, prevention and responsible waste management matter every day.']}
};
const litterLayout=[{x:53,y:20,size:64,rotation:-26},{x:88,y:28,size:75,rotation:35},{x:68,y:14,size:58,rotation:72},{x:58,y:49,size:62,rotation:-65},{x:92,y:47,size:55,rotation:120},{x:80,y:12,size:48,rotation:14},{x:47,y:38,size:66,rotation:45},{x:78,y:50,size:63,rotation:-110}];
function oceanMood(){return wasteLevel===0?'green':wasteLevel<5?'orange':'red'}
function renderOcean(recovered=false){const mood=oceanMood(),s=oceanStories[mood];scene.dataset.mood=mood;scene.style.setProperty('--pollution',String(wasteLevel/8));scene.classList.toggle('story-restored',recovered&&wasteLevel===0);turtleImage.alt=`RevoWaste turtle in ${mood==='orange'?'amber':mood}, symbolising ${s.state.toLowerCase()}`;document.querySelector('#turtle-kicker').textContent=s.kicker;document.querySelector('#turtle-title').textContent=recovered&&wasteLevel===0?'A different ending starts with us.':s.title;document.querySelector('#turtle-story').textContent=recovered&&wasteLevel===0?'The scene is clear again. In the real world, keeping waste out of nature starts with how we manage it on land.':s.story;document.querySelector('#ocean-state').textContent=s.state;document.querySelector('#ocean-count').textContent=wasteLevel?`${wasteLevel} discarded item${wasteLevel===1?'':'s'} in this scene`:'No waste in this scene';wasteSlider.value=wasteLevel;wasteSlider.setAttribute('aria-valuetext',`${wasteLevel} waste items. ${s.state.toLowerCase()}`);document.querySelector('#add-waste').disabled=wasteLevel>=8;document.querySelector('#recover-waste').disabled=wasteLevel===0||recoveryTimer!==null;
 for(let i=0;i<8;i++){const existing=document.querySelector(`#ocean-litter-${i}`);if(i<wasteLevel&&!existing){const img=document.createElement('img');img.id=`ocean-litter-${i}`;img.className='ocean-litter';img.src='waste-bottle.png';img.alt='';const l=litterLayout[i];img.style.setProperty('--x',l.x+'%');img.style.setProperty('--y',l.y+'%');img.style.setProperty('--size',l.size+'px');img.style.setProperty('--rotation',l.rotation+'deg');litterField.append(img)}else if(i>=wasteLevel&&existing){existing.removeAttribute('id');existing.classList.add('is-recovering');setTimeout(()=>existing.remove(),motionPaused||reducedMotion.matches?0:1000)}}}
function stopRecovery(){if(recoveryTimer!==null){clearInterval(recoveryTimer);recoveryTimer=null}document.querySelector('#recover-waste').textContent='Change the outcome'}
document.querySelector('#add-waste').addEventListener('click',()=>{manualStory=true;stopRecovery();wasteLevel=Math.min(8,wasteLevel+1);tipIndex=0;renderOcean()});
wasteSlider.addEventListener('input',()=>{manualStory=true;stopRecovery();const before=wasteLevel;wasteLevel=Number(wasteSlider.value);renderOcean(wasteLevel<before)});
document.querySelector('#recover-waste').addEventListener('click',()=>{manualStory=true;if(!wasteLevel)return;stopRecovery();if(motionPaused||reducedMotion.matches){wasteLevel=0;renderOcean(true);return}document.querySelector('#recover-waste').textContent='Recovering…';recoveryTimer=setInterval(()=>{wasteLevel=Math.max(0,wasteLevel-1);if(wasteLevel===0)stopRecovery();renderOcean(true)},650);renderOcean()});
document.querySelector('#reset-ocean').addEventListener('click',()=>{stopRecovery();manualStory=false;wasteLevel=0;tipIndex=0;renderOcean();document.querySelector('#ocean-chapter').scrollIntoView({behavior:reducedMotion.matches?'instant':'smooth'})});
turtleButton.addEventListener('click',()=>{const s=oceanStories[oceanMood()];document.querySelector('#turtle-story').textContent=s.tips[tipIndex%s.tips.length];tipIndex++;if(!motionPaused&&!reducedMotion.matches){turtleButton.classList.remove('nudge');requestAnimationFrame(()=>turtleButton.classList.add('nudge'))}});
turtleButton.addEventListener('animationend',()=>turtleButton.classList.remove('nudge'));
scene.addEventListener('pointermove',e=>{if(motionPaused||reducedMotion.matches||e.pointerType==='touch')return;const r=scene.getBoundingClientRect();scene.style.setProperty('--pointer-x',((e.clientX-r.left)/r.width-.5)*20+'px');scene.style.setProperty('--pointer-y',((e.clientY-r.top)/r.height-.5)*16+'px')});
scene.addEventListener('pointerleave',()=>{scene.style.setProperty('--pointer-x','0px');scene.style.setProperty('--pointer-y','0px')});
function updateMotion(){scene.classList.toggle('motion-paused',motionPaused);const b=document.querySelector('#motion-toggle');b.setAttribute('aria-pressed',String(motionPaused));b.textContent=motionPaused?'Resume motion':'Pause motion';if(reducedMotion.matches){b.textContent='Reduced motion';b.disabled=true}if(motionPaused&&recoveryTimer!==null){stopRecovery();renderOcean()}}
document.querySelector('#motion-toggle').addEventListener('click',()=>{motionPaused=!motionPaused;updateMotion()});reducedMotion.addEventListener('change',()=>{motionPaused=reducedMotion.matches;document.querySelector('#motion-toggle').disabled=false;updateMotion()});updateMotion();renderOcean();

// Scroll is an introduction only. Direct interaction always takes priority.
let storyFrame=0;
function followOceanScroll(){storyFrame=0;const chapter=document.querySelector('#ocean-chapter');const rect=chapter.getBoundingClientRect();const total=chapter.offsetHeight-window.innerHeight;const progress=Math.max(0,Math.min(1,(100-rect.top)/Math.max(total,1)));scene.style.setProperty('--story-progress',progress);if(!manualStory&&!motionPaused&&!reducedMotion.matches&&window.matchMedia('(min-width: 901px)').matches){const next=Math.min(8,Math.floor(Math.max(0,progress-.12)*12));if(next!==wasteLevel){wasteLevel=next;renderOcean()}}}
window.addEventListener('scroll',()=>{if(!storyFrame)storyFrame=requestAnimationFrame(followOceanScroll)},{passive:true});window.addEventListener('resize',followOceanScroll);followOceanScroll();

const cartridgeNotes=[['01 / MANUAL DISMANTLING','A careful first step.','Cartridges are dismantled by hand so their different components can be separated. A small office item becomes a collection of materials with further potential.'],['02 / MATERIAL SEPARATION','Keep the useful parts apart.','Separating the fractions is central to the process. It allows suitable materials to follow reuse and recycling routes, instead of treating the whole cartridge as waste.'],['03 / MATERIAL RECOVERY','An empty cartridge still has value.','RevoWaste reports a 99% cartridge recycling rate, with less than 1% going to landfill. Speak to the team about your cartridge waste and collection requirements.']];
function showCartridge(i){document.querySelectorAll('[data-cartridge]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.cartridge)===i)));const n=cartridgeNotes[i];document.querySelector('#cartridge-explanation').innerHTML=`<p class="eyebrow">${n[0]}</p><h3>${n[1]}</h3><p>${n[2]}</p><a class="button" href="#contact">Discuss cartridge recycling</a>`;document.querySelector('#cartridge-explanation a').onclick=()=>document.querySelector('#enquiry [name=stream]').value='Printer cartridges';}
document.querySelectorAll('[data-cartridge]').forEach(b=>b.onclick=()=>showCartridge(Number(b.dataset.cartridge)));showCartridge(0);
const galleryImages=[['pr3.jpg','cartridges','Used cartridges awaiting a recovery route'],['pr2.jpg','cartridges','Different cartridges, one specialist waste stream'],['item-7.jpg','electronics','Separating electronic components'],['p2.jpg','plastics','Plastic flakes after granulation'],['p4.jpg','plastics','Pellets for further manufacturing'],['step4.jpg','facility','RevoWaste facility exterior']];
const galleryGrid=document.querySelector('#gallery-grid');galleryGrid.innerHTML=galleryImages.map((g,i)=>`<button class="gallery-item" data-category="${g[1]}" data-photo="${i}" aria-label="Enlarge: ${g[2]}"><img src="${assetUrl(''+g[0])}" alt="${g[2]}" loading="lazy"><span>${g[2]}</span></button>`).join('');
document.querySelectorAll('[data-gallery-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-gallery-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('.gallery-item').forEach(x=>x.hidden=b.dataset.galleryFilter!=='all'&&x.dataset.category!==b.dataset.galleryFilter)});
const photoDialog=document.querySelector('#photo-dialog');let photoTrigger=null;
galleryGrid.onclick=e=>{const b=e.target.closest('[data-photo]');if(!b)return;photoTrigger=b;const g=galleryImages[Number(b.dataset.photo)];document.querySelector('#photo-full').src=assetUrl(''+g[0]);document.querySelector('#photo-full').alt=g[2];document.querySelector('#photo-caption').textContent=g[2];photoDialog.showModal()};
photoDialog.querySelector('button').onclick=()=>photoDialog.close();photoDialog.addEventListener('click',e=>{if(e.target===photoDialog){const r=photoDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)photoDialog.close()}});photoDialog.addEventListener('close',()=>photoTrigger?.focus());
